import "./globals.css";
import '@mantine/core/styles.css';
import { MantineProvider } from "@mantine/core";

export const metadata = {
  title: "Yant Furniture",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=''>
        <MantineProvider>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
